name: http_cookie_store
description: Process and store cookies in a cookie store, or directly use it as a http client.
version: 0.0.1
repository: https://github.com/Dampfwalze/http_cookie_store

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  http: ^1.1.0
  quiver: ^3.2.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
